name: ce2006_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.1
  geolocator: ^8.0.3
  provider: ^6.0.2
  fluttertoast: ^8.0.8
  animated_text_kit: ^4.2.1
  flutter_spinkit: ^5.1.0
  flutter_switch: ^0.3.2
  http: ^0.13.4
  url_launcher: ^6.0.20
  android_intent_plus: ^3.1.1
  flutter_google_places: ^0.3.0
  charts_flutter: ^0.12.0
  speech_to_text: ^5.4.3
  flutter_polyline_points: ^1.0.0
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  avatar_glow: ^2.0.2
  google_mobile_ads: ^1.2.0
  restart_app: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplaySC-Regular.otf
    - family: Source Sans Pro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.otf
        - asset: assets/fonts/SourceSansPro-Bold.otf
          weight: 700
        - asset: assets/fonts/SourceSansPro-It.otf
          style: italic